document.write("<nav class=\"navbar navbar-default navbar-fixed-top\">");
document.write("        <div class=\"container\">");
document.write("            <!-- Brand and toggle get grouped for better mobile display -->");
document.write("            <div class=\"navbar-header page-scroll\">");
document.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">");
document.write("                    <span class=\"sr-only\">Toggle navigation<\/span>");
document.write("                    <span class=\"icon-bar\"><\/span>");
document.write("                    <span class=\"icon-bar\"><\/span>");
document.write("                    <span class=\"icon-bar\"><\/span>");
document.write("                <\/button>");
document.write("                <a class=\"navbar-brand\" href=\"..\/index.html\">CodeCult<\/a>");
document.write("            <\/div>");
document.write("");
document.write("            <!-- Collect the nav links, forms, and other content for toggling -->");
document.write("            <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">");
document.write("                <ul class=\"nav navbar-nav navbar-right\">");
document.write("                    <li class=\"hidden\">");
document.write("                        <a href=\"#page-top\"><\/a>");
document.write("                    <\/li>");
document.write("                    <li class=\"page-scroll\">");
document.write("                        <div class=\"dropdown\">");
document.write("                          <button class=\"btn btn-default dropdown-toggle\" type=\"button\" id=\"dropdownMenu1\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"true\">");
document.write("                            Voor scholen");
document.write("                            <span class=\"caret\"><\/span>");
document.write("                          <\/button>");
document.write("                          <ul class=\"dropdown-menu\" aria-labelledby=\"dropdownMenu1\">");
document.write("                            <li><a href=\"basisschool.html\">Basisscholen<\/a><\/li>");
document.write("                            <!--<li><a href=\"middelbarescholen.html\">Middelbare scholen<\/a><\/li>-->");
document.write("                          <\/ul>");
document.write("                        <\/div>");
document.write("                    <\/li>");
document.write("                  <li class=\"page-scroll\">");
document.write("                        <div class=\"dropdown\">");
document.write("                          <button class=\"btn btn-default dropdown-toggle\" type=\"button\" id=\"dropdownMenu1\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"true\">");
document.write("                            Voor particulieren");
document.write("                            <span class=\"caret\"><\/span>");
document.write("                          <\/button>");
document.write("                          <ul class=\"dropdown-menu\" aria-labelledby=\"dropdownMenu1\">");
document.write("                            <li><a href=\"kinderen.html\">Kinderen<\/a><\/li>");
document.write("                            <!--<li><a href=\"volwassenen.html\">Volwassenen<\/a><\/li>-->");
document.write("                            <li><a href=\"resources.html\">Tips voor zelfstudie<\/a><\/li>");
document.write("                          <\/ul>");
document.write("                        <\/div>");
document.write("                    <\/li>");
document.write("                    <li class=\"page-scroll\">");
document.write("                       <div class=\"dropdown\">");
document.write("                          <button class=\"btn btn-default dropdown-toggle\" type=\"button\" id=\"dropdownMenu1\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"true\">");
document.write("                            Voor bedrijven");
document.write("                            <span class=\"caret\"><\/span>");
document.write("                          <\/button>");
document.write("                          <ul class=\"dropdown-menu\" aria-labelledby=\"dropdownMenu1\">");
document.write("                            <li><a href=\"sponsoring.html\">Help CodeCult<\/a><\/li>");
document.write("                          <\/ul>");
document.write("                        <\/div>");
document.write("                    <\/li>");
document.write("                    <!-- Ik heb hier dropdowns van gemaakt omdat dat een snelle manier was om de layout consistent te houden...maar het is niet echt nodig qua inhoud-->");
document.write("                   <li class=\"page-scroll\">");
document.write("                          <button class=\"btn btn-default\" type=\"button\" id=\"dropdownMenu1\" >");
document.write("                                <li><a href=\"codeherfst.html\">CodeHerfst<\/a><\/li>");
document.write("                          <\/button>");
document.write("                            <!-- <li><a href=\"codeherfst.html\">CodeHerfst<\/a><\/li> -->");
document.write("                    <\/li>");
document.write("                    ");
document.write("                    <li class=\"page-scroll\">");
document.write("                        <div class=\"dropdown\">");
document.write("                          <button class=\"btn btn-default dropdown-toggle\" type=\"button\" id=\"dropdownMenu1\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"true\">");
document.write("                            Ons team");
document.write("                            <span class=\"caret\"><\/span>");
document.write("                          <\/button>");
document.write("");
document.write("                          <ul class=\"dropdown-menu\" aria-labelledby=\"dropdownMenu1\">");
document.write("                            <li><a href=\"trainers.html#Eszter\">Eszter Fodor, <span style=\"text-transform:none\">BSc<\/span><\/a><\/li>");
document.write("                            <li><a href=\"trainers.html#Elise\">Elise van der Pol, <span style=\"text-transform:none\">BSc<\/span><\/a><\/li>");
document.write("                            <li><a href=\"trainers.html#Erika\">Erika Schlatter, <span style=\"text-transform:none\">BSc<\/span><\/a><\/li>");
document.write("                            <li><a href=\"trainers.html#Timo\">Timo Mulder, <span style=\"text-transform:none\">BSc<\/span><\/a><\/li>");
document.write("                          <\/ul>");
document.write("                        <\/div>                        ");
document.write("                    <\/li>");
document.write("                <\/ul>");
document.write("            <\/div>");
document.write("            <!-- \/.navbar-collapse -->");
document.write("        <\/div>");
document.write("        <!-- \/.container-fluid -->");
document.write("    <\/nav>");
